module.exports={
    siteMetadata:{
        title:"Blogs for the day",
        author:"Piyush Deharia"
    },
    plugins:[
        'gatsby-plugin-react-helmet',
        {
            resolve:'gatsby-source-contentful',
            options:{
                spaceId:'7qnaui911a4a',
                accessToken:'24wkW0xZwMosrmyim5omKBM1uuV9DfGZ0hpGFlqoy8Y'
            }
        },
        'gatsby-plugin-sass',
        {
            resolve:'gatsby-source-filesystem',
            options:{
                name:'src',
                path:`${__dirname}/src/`
            }
        },
        'gatsby-plugin-sharp',
        {
            resolve:"gatsby-transformer-remark"
            ,options:{
                plugins:[
                    'gatsby-remark-relative-images',
                    {
                        resolve:'gatsby-remark-images',
                        options:{
                            maxWidth:750,
                            linkImagesToOriginal:false
                        }
                    }
                ]
            }
        }
    ]
}